# Plotting exchange results



In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd



## Exchange parameters extraction
Let us start with solving the 3-electron problem.
If we disregard the exchange between the first and the third dot in the chain
($J_{31}=0$), the Heisenberg Hamiltonian diagonalizes with the eigenvalues 
$\epsilon_1< \epsilon_2 < \epsilon_3$ that relate to the exchange values 
in the following way:
$$
\alpha = 2 (\epsilon_2 -\epsilon_1)  - (\epsilon_3 -\epsilon_1), 
\quad
\beta = \frac{1}{3}\sqrt{4(\epsilon_3 -\epsilon_1)^2-\alpha^2};
\qquad J_{12}, J_{23} =\frac{\alpha \pm \beta}{2}
$$

For a symmetric system ($J_{12}=J_{23}=J$) we must obtain
 $$\epsilon_2-\epsilon_1 = J, \quad  \epsilon_3 - \epsilon_2= J/2$$

Defining the function to extract the exchange values: 

In [2]:

#extract exchange

def ex_3_dots(e):
    
    alpha = 2 * (e[:,2] - e[:,1]) + (e[:,1] - e[:,0])
    beta = 1/3 *  np.sqrt((4 * np.square(e[:,1] - e[:,0])  - np.square(alpha)))
    return ( np.array((1 / 2 * (alpha + beta), 1 / 2 * np.abs(alpha - beta) ))).T


In [3]:
ns = range(10,15)
allens = np.array([
    [-1.85667615e-20, -1.85325092e-20, -1.84906540e-20, 
-1.84564018e-20,
 -1.84564018e-20, -1.84564018e-20],
 [-1.86250639e-20, -1.86098759e-20, -1.85389419e-20, -1.85237539e-20,
 -1.85237539e-20, -1.85237539e-20],
 [-1.86372346e-20, -1.86098759e-20, -1.85632834e-20, -1.85359247e-20,
 -1.85359247e-20, -1.85359247e-20],
[-1.86806964e-20, -1.86767027e-20, -1.85997607e-20, -1.85957670e-20,
 -1.85957670e-20, -1.85957670e-20],
[-1.86856348e-20, -1.86806964e-20, -1.86096375e-20, -1.86046991e-20,
 -1.86046991e-20, -1.86046991e-20]], dtype='complex128'
)

ex_3_dots(allens)

array([[5.89813500e-23+1.60054838e-23j, 6.11144431e-23+0.00000000e+00j],
       [7.85280000e-23+2.56817519e-23j, 8.26208156e-23+0.00000000e+00j],
       [6.02718500e-23+1.79015748e-23j, 6.28741782e-23+0.00000000e+00j],
       [7.89388500e-23+2.62792533e-23j, 8.31982043e-23+0.00000000e+00j],
       [7.35281000e-23+2.44540242e-23j, 7.74879396e-23+0.00000000e+00j]])

# Testing the numpy fancy indexing

In [4]:
n_se_so = 6666
map_so_basis = np.zeros((n_se_so, 2));
import time
init = time.time_ns()
for idx in range(n_se_so):
    map_so_basis[idx, :] = [idx // 2, idx % 2]
fin = time.time_ns() - init

print('time for for loop:\t', fin)

init = time.time_ns()
inds = np.arange(n_se_so)
map_so_basis[inds, :]= np.array([inds // 2, inds % 2]).T

fin = time.time_ns() - init
print('time for numpy array:\t', fin)

time for for loop:	 6020000
time for numpy array:	 1002200


In [5]:
from scipy.io import loadmat
from scipy.interpolate import interp1d

mat_contents = loadmat('N=2_4_6_8_10_M=15')
mat_contents.keys()

dict_keys(['__header__', '__version__', '__globals__', 'exchange'])

In [6]:
mat_exchanges = mat_contents['exchange']
mat_dot_seps = np.linspace(7.5,15,100) * 2
mat_exchanges.T[:,:10]

array([[0.06801233, 0.06790605, 0.06779017, 0.06765759, 0.06743864,
        0.06720182, 0.06694786, 0.0666786 , 0.06638932, 0.06608526],
       [0.01489736, 0.01451815, 0.01415002, 0.0137925 , 0.01344515,
        0.01310763, 0.01277952, 0.01246044, 0.01215009, 0.0118481 ],
       [0.01949865, 0.018899  , 0.01832052, 0.01776227, 0.01722345,
        0.01670322, 0.01620077, 0.01571542, 0.0152464 , 0.01479306],
       [0.01355621, 0.01298857, 0.01244378, 0.01192089, 0.01141901,
        0.01093728, 0.01047488, 0.01003101, 0.00960492, 0.00919591],
       [0.01266595, 0.01212384, 0.01160388, 0.0111052 , 0.01062686,
        0.01016809, 0.00972804, 0.00930595, 0.00890108, 0.00851273],
       [0.01289593, 0.01234608, 0.01181859, 0.01131254, 0.01082703,
        0.01036123, 0.00991434, 0.00948558, 0.00907422, 0.00867954]])

Adding the exchange values from Python code

In [7]:
exchange_values = np.array([3.272889639370402e-21, 2.913048883523661e-21,  
             2.7635322566316486e-21, 5.420431755732095e-22, 5.293272032143253e-23, 
             2.4903525929608842e-21, 2.4903525929608842e-21, 1.5720630064745896e-21   ])

interpolated_exchanges = interp1d(mat_dot_seps, mat_exchanges[:,0])

interpolated_exchanges(np.linspace(15,30,10)[:8])  / exchange_values

array([2.07805156e+19, 2.24609311e+19, 2.19874243e+19, 1.00574369e+20,
       8.87766558e+20, 1.54875725e+19, 1.19649399e+19, 1.35728523e+19])

In [8]:

%matplotlib widget
legends = ('N=2','N=4','N=6','N=8','N=10', 'N=8 data')

plt.figure(figsize=(6,5))
for ex in mat_exchanges.T:
    plt.plot(mat_dot_seps, ex * 42.7E3)
#plt.legend(plot, legends)

plt.plot(np.linspace(15,30,10)[:8], exchange_values/1.6e-25, 'r.' )
plt.xscale('linear')
plt.yscale('log')
plt.legend(legends, loc='best', fancybox=True, ncol=2)
plt.xlim((15,30))

plt.show()


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …